[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/=lib/chainlink-local/lib/chainlink-evm/contracts/src",
"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
